// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLResource" GDExtension class.</summary>
public partial class FSLResource
{
    public static readonly StringName GDClassName = "FSLResource";

    /// <summary>The underlying GDExtension object; pass this to Godot APIs.</summary>
    public RefCounted Inner { get; }

    public FSLResource(GodotObject inner)
    {
        Inner = (RefCounted)inner;
    }

    public static implicit operator Variant(FSLResource wrapper) => wrapper?.Inner ?? default;
}
