// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLTexture" GDExtension class.</summary>
public partial class FSLTexture : FSLResource
{
    public new static readonly StringName GDClassName = "FSLTexture";

    public FSLTexture(GodotObject inner) : base(inner) { }

    public FSLTexture() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public void BindCallback(Callable callback) => Inner.Call(MethodName.BindCallback, callback);

    public void Set2DTexture(uint texWidth, uint texHeight, Image image = null) => Inner.Call(MethodName.Set2DTexture, texWidth, texHeight, image);

    public void Set3DTexture(uint texWidth, uint texHeight, uint texDepth, Godot.Collections.Array<Image> images = null) => Inner.Call(MethodName.Set3DTexture, texWidth, texHeight, texDepth, images ?? new Godot.Collections.Array<Image>());

    public static class MethodName
    {
        public static readonly StringName BindCallback = "bind_callback";
        public static readonly StringName Set2DTexture = "set_2d_texture";
        public static readonly StringName Set3DTexture = "set_3d_texture";
    }
}
