// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "ComputeKernel" GDExtension class.</summary>
public partial class ComputeKernel
{
    public static readonly StringName GDClassName = "ComputeKernel";

    /// <summary>The underlying GDExtension object; pass this to Godot APIs.</summary>
    public RefCounted Inner { get; }

    public ComputeKernel(GodotObject inner)
    {
        Inner = (RefCounted)inner;
    }

    public ComputeKernel() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public static implicit operator Variant(ComputeKernel wrapper) => wrapper?.Inner ?? default;

    public enum BufferType : long
    {
        Storage = 0,
        Uniform = 1,
    }

    public enum TextureFormat : long
    {
        Rgba32F = 0,
        Rgba16F = 1,
    }

    public void PrintInfo() => Inner.Call(MethodName.PrintInfo);

    public void Dispatch(uint xInvocations, uint yInvocations, uint zInvocations, Godot.Collections.Dictionary<StringName, Variant> pushConstants = null) => Inner.Call(MethodName.Dispatch, xInvocations, yInvocations, zInvocations, pushConstants ?? new Godot.Collections.Dictionary<StringName, Variant>());

    public void DispatchWorkgroups(uint xWorkgroups, uint yWorkgroups, uint zWorkgroups, Godot.Collections.Dictionary<StringName, Variant> pushConstants = null) => Inner.Call(MethodName.DispatchWorkgroups, xWorkgroups, yWorkgroups, zWorkgroups, pushConstants ?? new Godot.Collections.Dictionary<StringName, Variant>());

    public void AssignResource(FSLResource resource, StringName resourceName) => Inner.Call(MethodName.AssignResource, resource?.Inner, resourceName);

    public FSLBuffer GetBuffer(StringName bufferName)
    {
        GodotObject result = Inner.Call(MethodName.GetBuffer, bufferName).AsGodotObject();
        return result == null ? null : new FSLBuffer(result);
    }

    public FSLTexture GetTexture(StringName textureName)
    {
        GodotObject result = Inner.Call(MethodName.GetTexture, textureName).AsGodotObject();
        return result == null ? null : new FSLTexture(result);
    }

    public void BufferBindCallback(StringName bufferName, Callable callback) => Inner.Call(MethodName.BufferBindCallback, bufferName, callback);

    public void BufferSetUnsizedElementCount(StringName bufferName, uint elementCount) => Inner.Call(MethodName.BufferSetUnsizedElementCount, bufferName, elementCount);

    public void TextureBindCallback(StringName textureName, Callable callback) => Inner.Call(MethodName.TextureBindCallback, textureName, callback);

    public void TextureSet2D(StringName textureName, uint width, uint height, Image tex = null) => Inner.Call(MethodName.TextureSet2D, textureName, width, height, tex);

    public void TextureSet3D(StringName textureName, uint width, uint height, uint depth, Godot.Collections.Array<Image> images = null) => Inner.Call(MethodName.TextureSet3D, textureName, width, height, depth, images ?? new Godot.Collections.Array<Image>());

    public static class MethodName
    {
        public static readonly StringName PrintInfo = "print_info";
        public static readonly StringName Dispatch = "dispatch";
        public static readonly StringName DispatchWorkgroups = "dispatch_workgroups";
        public static readonly StringName AssignResource = "assign_resource";
        public static readonly StringName GetBuffer = "get_buffer";
        public static readonly StringName GetTexture = "get_texture";
        public static readonly StringName BufferBindCallback = "buffer_bind_callback";
        public static readonly StringName BufferSetUnsizedElementCount = "buffer_set_unsized_element_count";
        public static readonly StringName TextureBindCallback = "texture_bind_callback";
        public static readonly StringName TextureSet2D = "texture_set_2d";
        public static readonly StringName TextureSet3D = "texture_set_3d";
    }
}
