// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLBuffer" GDExtension class.</summary>
public partial class FSLBuffer : FSLResource
{
    public new static readonly StringName GDClassName = "FSLBuffer";

    public FSLBuffer(GodotObject inner) : base(inner) { }
}
