// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLFile" GDExtension class.</summary>
public partial class FSLFile
{
    public static readonly StringName GDClassName = "FSLFile";

    /// <summary>The underlying GDExtension object; pass this to Godot APIs.</summary>
    public RefCounted Inner { get; }

    public FSLFile(GodotObject inner)
    {
        Inner = (RefCounted)inner;
    }

    public FSLFile() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public static implicit operator Variant(FSLFile wrapper) => wrapper?.Inner ?? default;

    public void Test() => Inner.Call(MethodName.Test);

    public static FSLFile FromFile(string filePath)
    {
        GodotObject result = ClassDB.ClassCallStatic(GDClassName, MethodName.FromFile, filePath).AsGodotObject();
        return result == null ? null : new FSLFile(result);
    }

    public string GetKernelSource(StringName kernelName) => Inner.Call(MethodName.GetKernelSource, kernelName).As<string>();

    public ComputeKernel GetKernel(StringName kernelName, RenderingDevice renderingDevice = null)
    {
        GodotObject result = Inner.Call(MethodName.GetKernel, kernelName, renderingDevice).AsGodotObject();
        return result == null ? null : new ComputeKernel(result);
    }

    public ComputeGroup GetKernelGroup(RenderingDevice renderingDevice = null)
    {
        GodotObject result = Inner.Call(MethodName.GetKernelGroup, renderingDevice).AsGodotObject();
        return result == null ? null : new ComputeGroup(result);
    }

    public static class MethodName
    {
        public static readonly StringName Test = "test";
        public static readonly StringName FromFile = "from_file";
        public static readonly StringName GetKernelSource = "get_kernel_source";
        public static readonly StringName GetKernel = "get_kernel";
        public static readonly StringName GetKernelGroup = "get_kernel_group";
    }
}
