// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLTexture" GDExtension class.</summary>
public partial class FSLTexture : FSLResource
{
    public new static readonly StringName GDClassName = "FSLTexture";

    public FSLTexture(GodotObject inner) : base(inner) { }
}
