// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLVertexBuffer" GDExtension class.</summary>
public partial class FSLVertexBuffer : FSLBuffer
{
    public new static readonly StringName GDClassName = "FSLVertexBuffer";

    public FSLVertexBuffer(GodotObject inner) : base(inner) { }

    public FSLVertexBuffer() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }
}
