#!/usr/bin/env python3
"""Generate C# wrapper classes for the FSL GDExtension from a JSON manifest.

The manifest (bindings/csharp_manifest.json) is the single source of truth:
every exposed class, method, argument and type is emitted exactly as declared
there, with nothing inferred from ClassDB reflection. Wrappers hold the
underlying GDExtension object (created via ClassDB) and forward calls through
Variant `Call`, which is the only way C# can talk to a C++ GDExtension class.

See bindings/README.md for the manifest schema.

Usage:
    generate_csharp_bindings.py [--manifest PATH] [--out DIR]
"""

import argparse
import json
import os
import sys

HEADER = """// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

"""


def pascal(snake):
    """Default snake_case -> PascalCase conversion; override per-entry with "csharp"."""
    parts = []
    for part in snake.split("_"):
        if not part:
            continue
        if part[0].isdigit():
            # e.g. "2d" -> "2D", matching Godot's C# naming for engine classes.
            parts.append(part[0] + part[1:].upper())
        else:
            parts.append(part[0].upper() + part[1:])
    return "".join(parts)


def camel(snake):
    name = pascal(snake)
    return name[0].lower() + name[1:] if name else name


class Generator:
    def __init__(self, manifest):
        self.namespace = manifest.get("namespace", "FluxxiShaderLang")
        self.classes = manifest["classes"]
        # Engine-side enum types (e.g. "RenderingDevice.UniformType") that
        # must round-trip through long like declared enums.
        self.engine_enums = set(manifest.get("engine_enums", []))
        # "Class.Enum" qualified names of every declared enum, for type resolution.
        self.enum_names = {
            "{}.{}".format(cls, enum)
            for cls, spec in self.classes.items()
            for enum in spec.get("enums", {})
        }
        for cls, spec in self.classes.items():
            parent = spec.get("extends")
            if parent is not None and parent not in self.classes:
                raise ValueError('class "{}" extends unknown class "{}"'.format(cls, parent))
            if parent is not None and "base" in spec:
                raise ValueError('class "{}" declares both "extends" and "base"'.format(cls))

    def ancestors(self, cls):
        parent = self.classes[cls].get("extends")
        while parent is not None:
            yield parent
            parent = self.classes[parent].get("extends")

    def root_of(self, cls):
        """The root of the wrapper hierarchy containing cls (cls itself if standalone)."""
        root = cls
        for root in self.ancestors(cls):
            pass
        return root

    def engine_base(self, cls):
        """The nearest engine class, taken from the root of the wrapper hierarchy."""
        return self.classes[self.root_of(cls)].get("base", "RefCounted")

    def concrete_descendants(self, cls):
        """Manifest-order descendants of cls that Godot can report via get_class()."""
        return [
            other for other, spec in self.classes.items()
            if other != cls and cls in self.ancestors(other)
            and not spec.get("abstract", False)
        ]

    def qualify_enum(self, type_name, cls):
        """Resolve a manifest type to a declared enum's qualified name, or None."""
        if type_name in self.engine_enums:
            return type_name
        if type_name in self.enum_names:
            return type_name
        unqualified = "{}.{}".format(cls, type_name)
        if unqualified in self.enum_names:
            return unqualified
        return None

    def arg_expr(self, arg, cls):
        """Expression converting a C# parameter into what Call() expects."""
        name = arg.get("csharp", camel(arg["name"]))
        type_name = arg["type"]
        if type_name in self.classes:
            return "{}?.Inner".format(name)
        if self.qualify_enum(type_name, cls) is not None:
            return "(long){}".format(name)
        if arg.get("default") == "null" and type_name.startswith("Godot.Collections."):
            # C++ side declares a (typed) Dictionary/Array default; nil is not
            # an acceptable substitute, so materialize an empty one.
            return "{} ?? new {}()".format(name, type_name)
        return name

    def emit_method(self, cls, method, lines):
        gd_name = method["name"]
        cs_name = method.get("csharp", pascal(gd_name))
        ret = method.get("return", "void")
        is_static = method.get("static", False)

        params = []
        for arg in method.get("args", []):
            param = "{} {}".format(arg["type"], arg.get("csharp", camel(arg["name"])))
            if "default" in arg:
                param += " = {}".format(arg["default"])
            params.append(param)
        signature = "public {}{} {}({})".format(
            "static " if is_static else "", ret, cs_name, ", ".join(params)
        )

        call_args = ["MethodName.{}".format(cs_name)]
        call_args += [self.arg_expr(arg, cls) for arg in method.get("args", [])]
        if is_static:
            # Requires Godot 4.4+ (ClassDB.class_call_static).
            call = "ClassDB.ClassCallStatic(GDClassName, {})".format(", ".join(call_args))
        else:
            call = "Inner.Call({})".format(", ".join(call_args))

        enum_type = self.qualify_enum(ret, cls)
        if ret == "void":
            lines.append("    {} => {};".format(signature, call))
        elif ret in self.classes:
            root = self.root_of(ret)
            cast = "" if ret == root else "({})".format(ret)
            lines.append("    {} => {}{}.Wrap({}.AsGodotObject());".format(
                signature, cast, root, call))
        elif enum_type is not None:
            lines.append("    {} => ({}){}.As<long>();".format(signature, enum_type, call))
        else:
            lines.append("    {} => {}.As<{}>();".format(signature, call, ret))
        lines.append("")

    def emit_property(self, cls, prop, lines):
        gd_name = prop["name"]
        cs_name = prop.get("csharp", pascal(gd_name))
        type_name = prop["type"]
        enum_type = self.qualify_enum(type_name, cls)
        get_call = "Inner.Get(PropertyName.{})".format(cs_name)
        lines.append("    public {} {}".format(type_name, cs_name))
        lines.append("    {")
        if type_name in self.classes:
            root = self.root_of(type_name)
            cast = "" if type_name == root else "({})".format(type_name)
            lines.append("        get => {}{}.Wrap({}.AsGodotObject());".format(cast, root, get_call))
            lines.append("        set => Inner.Set(PropertyName.{}, value?.Inner);".format(cs_name))
        elif enum_type is not None:
            lines.append("        get => ({}){}.As<long>();".format(enum_type, get_call))
            lines.append("        set => Inner.Set(PropertyName.{}, (long)value);".format(cs_name))
        else:
            lines.append("        get => {}.As<{}>();".format(get_call, type_name))
            lines.append("        set => Inner.Set(PropertyName.{}, value);".format(cs_name))
        lines.append("    }")
        lines.append("")

    def emit_name_cache(self, kind, entries, needs_new, lines):
        """A nested static class caching StringNames, like Godot's own C# classes."""
        lines.append("    public {}static class {}".format("new " if needs_new else "", kind))
        lines.append("    {")
        for cs_name, gd_name in entries:
            lines.append('        public static readonly StringName {} = "{}";'.format(cs_name, gd_name))
        lines.append("    }")
        lines.append("")

    def generate_class(self, cls):
        spec = self.classes[cls]
        parent = spec.get("extends")
        is_root = parent is None
        engine_base = self.engine_base(cls)
        methods = spec.get("methods", [])
        properties = spec.get("properties", [])
        signals = spec.get("signals", [])
        ancestor_specs = [self.classes[a] for a in self.ancestors(cls)]

        lines = [HEADER + "namespace {};".format(self.namespace), ""]
        lines.append('/// <summary>C# wrapper for the "{}" GDExtension class.</summary>'.format(cls))
        lines.append("public partial class {}{}".format(cls, " : {}".format(parent) if not is_root else ""))
        lines.append("{")
        lines.append('    public {}static readonly StringName GDClassName = "{}";'.format(
            "" if is_root else "new ", cls))
        lines.append("")

        if is_root:
            lines.append("    /// <summary>The underlying GDExtension object; pass this to Godot APIs.</summary>")
            lines.append("    public {} Inner {{ get; }}".format(engine_base))
            lines.append("")
            lines.append("    public {}(GodotObject inner)".format(cls))
            lines.append("    {")
            lines.append("        Inner = ({})inner;".format(engine_base))
            lines.append("    }")
        else:
            lines.append("    public {}(GodotObject inner) : base(inner) {{ }}".format(cls))
        lines.append("")

        if not spec.get("abstract", False):
            lines.append("    public {}() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) {{ }}".format(cls))
            lines.append("")

        if is_root:
            lines.append("    public static implicit operator Variant({} wrapper) => wrapper?.Inner ?? default;".format(cls))
            lines.append("")
            lines.append("    /// <summary>Wraps a GDExtension object in the most-derived C# wrapper for its Godot class.</summary>")
            descendants = self.concrete_descendants(cls)
            if descendants:
                lines.append("    public static {} Wrap(GodotObject inner) => inner?.GetClass() switch".format(cls))
                lines.append("    {")
                lines.append("        null => null,")
                for descendant in descendants:
                    lines.append('        "{}" => new {}(inner),'.format(descendant, descendant))
                lines.append("        _ => new {}(inner),".format(cls))
                lines.append("    };")
            else:
                lines.append("    public static {} Wrap(GodotObject inner) => inner == null ? null : new {}(inner);".format(cls, cls))
            lines.append("")

        for enum, values in spec.get("enums", {}).items():
            lines.append("    public enum {} : long".format(enum))
            lines.append("    {")
            for value_name, value in values.items():
                lines.append("        {} = {},".format(value_name, value))
            lines.append("    }")
            lines.append("")

        for method in methods:
            self.emit_method(cls, method, lines)
        for prop in properties:
            self.emit_property(cls, prop, lines)

        if methods:
            entries = [(m.get("csharp", pascal(m["name"])), m["name"]) for m in methods]
            self.emit_name_cache("MethodName", entries,
                                 any(a.get("methods") for a in ancestor_specs), lines)
        if properties:
            entries = [(p.get("csharp", pascal(p["name"])), p["name"]) for p in properties]
            self.emit_name_cache("PropertyName", entries,
                                 any(a.get("properties") for a in ancestor_specs), lines)
        if signals:
            entries = [(s.get("csharp", pascal(s["name"])), s["name"]) for s in signals]
            self.emit_name_cache("SignalName", entries,
                                 any(a.get("signals") for a in ancestor_specs), lines)

        while lines and lines[-1] == "":
            lines.pop()
        lines.append("}")
        return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    parser.add_argument("--manifest", default=os.path.join(script_dir, "csharp_manifest.json"))
    parser.add_argument("--out", default=os.path.join(
        script_dir, "..", "project", "addons", "fluxxishaderlang", "csharp"))
    args = parser.parse_args()

    with open(args.manifest) as manifest_file:
        manifest = json.load(manifest_file)

    generator = Generator(manifest)
    os.makedirs(args.out, exist_ok=True)
    for cls in generator.classes:
        path = os.path.join(args.out, "{}.cs".format(cls))
        with open(path, "w") as out:
            out.write(generator.generate_class(cls))
        print("generated {}".format(path))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, OSError) as error:
        print("generate_csharp_bindings: {}".format(error), file=sys.stderr)
        sys.exit(1)
